

name: CI

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - uses: actions/checkout@v3
      # - name: Install python version
      #  uses: gabrielfalcao/pyenv-action@v9
      #  with:
      #    default: 3.9.12
      #    command: pip install -U pip  # upgrade pip after installing python
      # - name: Install dependencies
      #  run: pip install -r requirements.txt
      
      # Run script manually
      - name: Run mlflow workflow
        run: |
          python wine_example/train.py
      
      # Run as a mlflow project
      # - name: Run mlflow project
      #  run: |
      #    mlflow run wine_example